
namespace OnlineBanking.Application.Features.BankAccounts.Create;

/// <summary>
/// Represents a request to create a new bank account.
/// Contains all account details, financial parameters, and associated customers.
/// </summary>
public class CreateBankAccountCommand : IRequest<ApiResult<Unit>>
{
    /// <summary>
    /// Gets the unique account number.
    /// If not provided, one will be auto-generated by the domain.
    /// </summary>
    public string AccountNo { get; private set; }

    /// <summary>
    /// Gets the International Bank Account Number (IBAN).
    /// Used for international transactions and transfers.
    /// </summary>
    public string IBAN { get; private set; }

    /// <summary>
    /// Gets the type of bank account (Savings, Current, Deposit, Joint).
    /// </summary>
    public BankAccountType Type { get; private set; }

    /// <summary>
    /// Gets the currency ID for the account.
    /// Determines which currency the account operates in.
    /// </summary>
    public int CurrencyId { get; private set; }

    /// <summary>
    /// Gets the branch ID that manages this account.
    /// </summary>
    public int BranchId { get; private set; }

    /// <summary>
    /// Gets the initial account balance.
    /// </summary>
    public decimal Balance { get; private set; }

    /// <summary>
    /// Gets the current debt on the account.
    /// </summary>
    public decimal Debt { get; private set; }

    /// <summary>
    /// Gets the maximum balance available for withdrawal or transfer.
    /// </summary>
    public decimal AllowedBalanceToUse { get; private set; }

    /// <summary>
    /// Gets the minimum balance required to maintain in the account.
    /// </summary>
    public decimal MinimumAllowedBalance { get; private set; }

    /// <summary>
    /// Gets the customer numbers of account owners.
    /// At least one customer is required.
    /// </summary>
    public string[] CustomerNos { get; private set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateBankAccountCommand"/> class.
    /// </summary>
    /// <param name="accountNo">The account number (will be auto-generated if empty)</param>
    /// <param name="iban">The IBAN</param>
    /// <param name="type">The account type</param>
    /// <param name="currencyId">The currency ID</param>
    /// <param name="branchId">The branch ID</param>
    /// <param name="balance">The initial balance</param>
    /// <param name="debt">The initial debt</param>
    /// <param name="allowedBalanceToUse">The allowed balance for withdrawal</param>
    /// <param name="minimumAllowedBalance">The minimum required balance</param>
    /// <param name="customerNos">The customer numbers (at least one required)</param>
    /// <exception cref="ArgumentNullException">Thrown when required parameters are null</exception>
    /// <exception cref="ArgumentException">Thrown when string parameters are empty or customerNos array is empty</exception>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when numeric parameters are invalid</exception>
    public CreateBankAccountCommand(
        string accountNo,
        string iban,
        BankAccountType type,
        int currencyId,
        int branchId,
        decimal balance,
        decimal debt,
        decimal allowedBalanceToUse,
        decimal minimumAllowedBalance,
        string[] customerNos)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(iban);

        if (currencyId <= 0)
            throw new ArgumentOutOfRangeException(nameof(currencyId), "Currency ID must be greater than 0");

        if (branchId <= 0)
            throw new ArgumentOutOfRangeException(nameof(branchId), "Branch ID must be greater than 0");

        if (balance < 0)
            throw new ArgumentOutOfRangeException(nameof(balance), "Initial balance cannot be negative");

        if (debt < 0)
            throw new ArgumentOutOfRangeException(nameof(debt), "Debt cannot be negative");

        if (minimumAllowedBalance < 0)
            throw new ArgumentOutOfRangeException(nameof(minimumAllowedBalance), "Minimum balance cannot be negative");

        if (allowedBalanceToUse < minimumAllowedBalance)
            throw new ArgumentException(
                "Allowed balance to use must be greater than or equal to minimum allowed balance",
                nameof(allowedBalanceToUse));

        AccountNo = accountNo;
        IBAN = iban;
        Type = type;
        CurrencyId = currencyId;
        BranchId = branchId;
        Balance = balance;
        Debt = debt;
        AllowedBalanceToUse = allowedBalanceToUse;
        MinimumAllowedBalance = minimumAllowedBalance;
        CustomerNos = customerNos;
    }
}